<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	  <TargetFramework>net9.0-windows10.0.22621.0</TargetFramework>
	  <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <RootNamespace>Verdure.Braincase.EbScreen</RootNamespace>
    <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &gt;= 8">win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <RuntimeIdentifiers Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &lt; 8">win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="ClockViews\Bubble.xaml" />
    <None Remove="ClockViews\CustomClockView.xaml" />
    <None Remove="ClockViews\GooeyFooter.xaml" />
    <None Remove="ClockViews\GradientsWithBlend.xaml" />
    <None Remove="ClockViews\GrooveClockView.xaml" />
    <None Remove="ClockViews\HiddenTextView.xaml" />
    <None Remove="ClockViews\LongShadow.xaml" />
  </ItemGroup>

  <ItemGroup>
	  <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.7.250310001" />
	  <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.1742" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Verdure.Braincase.WinUI.Common\Verdure.Braincase.WinUI.Common.csproj" />
    <ProjectReference Include="..\Mediapipe.Net\Mediapipe.Net.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="ClockViews\Bubble.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Page Update="ClockViews\CustomClockView.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="ClockViews\GooeyFooter.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="ClockViews\GradientsWithBlend.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="ClockViews\GrooveClockView.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
    </Page>
    <Page Update="ClockViews\HiddenTextView.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
    </Page>
    <Page Update="ClockViews\LongShadow.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
    </Page>
  </ItemGroup>
</Project>