<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>Verdure.Braincase.Core</RootNamespace>
    <Platforms>x86;x64;arm64;AnyCPU</Platforms>
    <ImplicitUsings>enable</ImplicitUsings>
	<Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	<PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
    <PackageReference Include="Microsoft.Graph" Version="5.61.0" />
    <PackageReference Include="Microsoft.Identity.Client.Broker" Version="4.66.1" />
    <PackageReference Include="Microsoft.Identity.Client.Extensions.Msal" Version="4.66.1" />
	  <PackageReference Include="Google.Protobuf" Version="3.28.3" />
	  <PackageReference Include="Grpc.Net.Client" Version="2.66.0" />
	  <PackageReference Include="Grpc.Net.ClientFactory" Version="2.66.0" />
	  <PackageReference Include="System.IO.Ports" Version="8.0.0" />
	  <PackageReference Include="SharpZipLib" Version="1.4.2" />
	  <PackageReference Include="Grpc.Tools" Version="2.67.0">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ElectronBot.DotNet\ElectronBot.DotNet.csproj" />
  </ItemGroup>
	<ItemGroup>
		<Protobuf Include="Protos\electronbotaction.proto" GrpcServices="Both" />
	</ItemGroup>

</Project>
