<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.22621.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <RootNamespace>Verdure.Braincase.Copilot</RootNamespace>
	<RuntimeIdentifiers Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &gt;= 8">win-x86;win-x64;win-arm64</RuntimeIdentifiers>
	<RuntimeIdentifiers Condition="$([MSBuild]::GetTargetFrameworkVersion('$(TargetFramework)')) &lt; 8">win10-x86;win10-x64;win10-arm64</RuntimeIdentifiers>
	<UseWinUI>true</UseWinUI>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Controls\Chat\ChatModuleHeader.xaml" />
    <None Remove="Controls\Chat\ChatModuleInput.xaml" />
    <None Remove="Controls\Chat\ChatModuleMsgItemControl.xaml" />
    <None Remove="Controls\Chat\ChatModuleMsgList.xaml" />
    <None Remove="Controls\Chat\ChatModulePanel.xaml" />
    <None Remove="Controls\Chat\ColorfulBorder.xaml" />
    <None Remove="Controls\Chat\PresetAvatar.xaml" />
    <None Remove="Controls\LingxiSpace\LingxiSpaceHeader.xaml" />
    <None Remove="Controls\LingxiSpace\LingxiSpaceList.xaml" />
    <None Remove="Controls\LingxiSpace\LingxiSpacePanel.xaml" />
    <None Remove="Styles\Overwrites.xaml" />
    <None Remove="Views\Agents\AgentPage.xaml" />
  </ItemGroup>

  <ItemGroup>
      <PackageReference Include="BotSharp.Abstraction" Version="3.0.0-verdure4" />
      <PackageReference Include="BotSharp.Core" Version="3.0.0-verdure4" />
      <PackageReference Include="BotSharp.Logger" Version="3.0.0-verdure4" />
      <PackageReference Include="BotSharp.Plugin.AzureOpenAI" Version="3.0.0-verdure4" />
      <PackageReference Include="BotSharp.Plugin.LiteDBStorage" Version="3.0.0-verdure4" />
      <PackageReference Include="BotSharp.Plugin.MetaGLM" Version="3.0.0-verdure4" />
      <PackageReference Include="BotSharp.Plugin.OpenAI" Version="3.0.0-verdure4" />
      <PackageReference Include="Microsoft.SemanticKernel" Version="1.32.0" />
      <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.6.241114003" />
      <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.1742" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Common\Verdure.Braincase.WinUI.Common\Verdure.Braincase.WinUI.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="Controls\Chat\ChatModulePanel.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Controls\Chat\ChatModuleHeader.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Controls\Chat\ColorfulBorder.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Controls\Chat\ChatModuleMsgItemControl.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Controls\Chat\PresetAvatar.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Controls\Chat\ChatModuleMsgList.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Controls\LingxiSpace\LingxiSpacePanel.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Controls\LingxiSpace\LingxiSpaceHeader.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Controls\LingxiSpace\LingxiSpaceList.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Views\Agents\AgentPage.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Controls\Chat\ChatModuleInput.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Page Update="Styles\Overwrites.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
</Project>
