<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net9.0-windows10.0.22621.0</TargetFramework>
	<TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
	<RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
	<UseWinUI>true</UseWinUI>
  </PropertyGroup>

    <ItemGroup>
	    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.7.250310001" />
	    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.1742" />
	    <PackageReference Include="Microsoft.CognitiveServices.Speech" Version="1.43.0" />
	    <PackageReference Include="NAudio" Version="2.2.1" />
	    <PackageReference Include="NetCoreAudio" Version="2.0.0" />
		<PackageReference Include="BotSharp.Core" Version="4.0.0-verdure1" />
		<PackageReference Include="System.Speech" Version="9.0.3" />
    </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Common\Verdure.Braincase.Core\Verdure.Braincase.Core.csproj" />
    <ProjectReference Include="..\..\Common\Verdure.Braincase.WinUI.Common\Verdure.Braincase.WinUI.Common.csproj" />
  </ItemGroup>

</Project>
