<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.22621.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <RootNamespace>Verdure.Braincase.EBConfiguration</RootNamespace>
    <RuntimeIdentifiers>win-x86;win-x64;win-arm64</RuntimeIdentifiers>
    <UseWinUI>true</UseWinUI>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Controls\Action\GamepadAction.xaml" />
    <None Remove="Views\EBDebugPage.xaml" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.1742" />
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.7.250310001" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\Common\Verdure.Braincase.WinUI.Common\Verdure.Braincase.WinUI.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Page Update="Controls\Action\EBLaunchAppList.xaml">
      <SubType>Designer</SubType>
    </Page>
    <Page Update="Controls\Action\GamepadAction.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  <ItemGroup>
    <Page Update="Views\EBDebugPage.xaml">
      <Generator>MSBuild:Compile</Generator>
    </Page>
    <Page Update="Views\EBLaunchAppPage.xaml">
      <XamlRuntime>$(DefaultXamlRuntime)</XamlRuntime>
      <Generator>MSBuild:Compile</Generator>
    </Page>
  </ItemGroup>
  
</Project>